# --- !Ups
ALTER TABLE D_FORM 
ADD COLUMN FORM_INDEX INT NOT NULL AFTER HASHED_ID,
ADD COLUMN NAME VARCHAR(255) NOT NULL AFTER FORM_INDEX,
ADD COLUMN TITLE VARCHAR(255) NOT NULL AFTER NAME,
ADD COLUMN STATUS INT NOT NULL AFTER TITLE,
ADD COLUMN CANCEL_URL VARCHAR(255) NOT NULL AFTER STATUS,
ADD COLUMN COMPLETE_URL VARCHAR(255) NOT NULL AFTER CANCEL_URL,
ADD COLUMN INPUT_HEADER LONGTEXT NULL AFTER COMPLETE_URL,
ADD COLUMN CONFIRM_HEADER LONGTEXT NULL AFTER INPUT_HEADER,
ADD COLUMN COMPLETE_TEXT LONGTEXT NULL AFTER CONFIRM_HEADER,
ADD COLUMN CLOSE_TEXT LONGTEXT NULL AFTER COMPLETE_TEXT;

# --- !Downs
ALTER TABLE D_FORM
DROP COLUMN FORM_INDEX,
DROP COLUMN NAME,
DROP COLUMN TITLE,
DROP COLUMN STATUS,
DROP COLUMN CANCEL_URL,
DROP COLUMN COMPLETE_URL,
DROP COLUMN INPUT_HEADER,
DROP COLUMN CONFIRM_HEADER,
DROP COLUMN COMPLETE_TEXT,
DROP COLUMN CLOSE_TEXT
