# --- !Ups
CREATE TABLE D_FORM_COL_VALIDATION (
  ID INT NOT NULL,
  FORM_COL_ID INT NOT NULL,
  FORM_ID INT NOT NULL,
  MAX_VALUE INT NULL,
  MIN_VALUE INT NULL,
  MAX_LENGTH INT NULL,
  MIN_LENGTH INT NULL,
  INPUT_TYPE INT NOT NULL,
  USER_GROUP VARCHAR(30) NOT NULL,
  CREATED_USER VARCHAR(45) NOT NULL,
  MODIFIED_USER VARCHAR(45) NOT NULL,
  CREATED VARCHAR(45) NOT NULL,
  MODIFIED VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID, FORM_COL_ID, FORM_ID),
  INDEX IDX_USER_GROUP (USER_GROUP ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

# --- !Downs
DROP TABLE D_FORM_COL_VALIDATION