# --- !Ups

ALTER TABLE `M_USER` ADD `UUID` varchar(50);
ALTER TABLE `M_USER` ADD `PROVIDER_ID` varchar(255);
ALTER TABLE `M_USER` ADD `PROVIDER_KEY` varchar(255);
ALTER TABLE `M_USER` ADD `FIRST_NAME` varchar(30);
ALTER TABLE `M_USER` ADD `LAST_NAME` varchar(30);
ALTER TABLE `M_USER` ADD `FULL_NAME` varchar(50);
ALTER TABLE `M_USER` ADD `AVATAR_URL` varchar(255);
ALTER TABLE `M_USER` ADD `ACTIVATED` tinyint;


# --- !Downs

ALTER TABLE `M_USER` DROP `UUID`;
ALTER TABLE `M_USER` DROP `PROVIDER_ID`;
ALTER TABLE `M_USER` DROP `PROVIDER_KEY`;
ALTER TABLE `M_USER` DROP `FIRST_NAME`;
ALTER TABLE `M_USER` DROP `LAST_NAME`;
ALTER TABLE `M_USER` DROP `FULL_NAME`;
ALTER TABLE `M_USER` DROP `AVATAR_URL`;
ALTER TABLE `M_USER` DROP `ACTIVATED`;
