# --- !Ups
DROP TABLE M_USER;

CREATE TABLE D_TRANSFER_CONFIG_MAIL (
ID INT NOT NULL AUTO_INCREMENT,
TRANSFER_CONFIG_ID INT NOT NULL,
SUBJECT VARCHAR(255) NOT NULL,
REPLY_TO VARCHAR(255) NULL,
FROM_ADDRESS VARCHAR(255) NOT NULL,
TO_ADDRESS VARCHAR(255) NOT NULL,
CC_ADDRESS VARCHAR(255) NULL,
BCC_ADDRESS VARCHAR(255) NULL,
BODY TEXT NULL,
USER_GROUP VARCHAR(30) NOT NULL,
CREATED_USER VARCHAR(45) NOT NULL,
MODIFIED_USER VARCHAR(45) NOT NULL,
CREATED DATETIME NOT NULL,
MODIFIED DATETIME NOT NULL,
PRIMARY KEY (ID),
INDEX IDX_TRANSFER_CONFIG_ID (TRANSFER_CONFIG_ID ASC) VISIBLE);

CREATE TABLE D_TRANSFER_CONFIG_SALESFORCE (
ID INT NOT NULL AUTO_INCREMENT,
TRANSFER_CONFIG_ID INT NOT NULL,
SF_USER_NAME VARCHAR(255) NOT NULL,
SF_PASSWORD VARCHAR(255) NOT NULL,
SF_SECURITY_TOKEN VARCHAR(255) NOT NULL,
USER_GROUP VARCHAR(30) NOT NULL,
CREATED_USER VARCHAR(45) NOT NULL,
MODIFIED_USER VARCHAR(45) NOT NULL,
CREATED DATETIME NOT NULL,
MODIFIED DATETIME NOT NULL,
PRIMARY KEY (ID),
INDEX IDX_TRANSFER_CONFIG_ID (TRANSFER_CONFIG_ID ASC) VISIBLE);


# --- !Downs
CREATE TABLE M_USER (
  ID int NOT NULL AUTO_INCREMENT,
  UID varchar(45) CHARACTER SET utf8 NOT NULL,
  NAME varchar(45) CHARACTER SET utf8 DEFAULT NULL,
  EMAIL varchar(100) CHARACTER SET utf8 NOT NULL,
  STATUS int NOT NULL,
  PASSWORD varchar(128) CHARACTER SET utf8 DEFAULT NULL,
  CREATED datetime DEFAULT NULL,
  MODIFIED datetime DEFAULT NULL,
  UUID varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  PROVIDER_ID varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  PROVIDER_KEY varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  FIRST_NAME varchar(30) CHARACTER SET utf8 DEFAULT NULL,
  LAST_NAME varchar(30) CHARACTER SET utf8 DEFAULT NULL,
  FULL_NAME varchar(50) CHARACTER SET utf8 DEFAULT NULL,
  AVATAR_URL varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  ACTIVATED tinyint DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

DROP TABLE D_TRANSFER_CONFIG_MAIL;

DROP TABLE D_TRANSFER_CONFIG_SALESFORCE;