# --- !Ups
ALTER TABLE D_TRANSFER_CONFIG_MAIL
DROP COLUMN BODY,
DROP COLUMN BCC_ADDRESS,
DROP COLUMN CC_ADDRESS,
DROP COLUMN TO_ADDRESS,
DROP COLUMN FROM_ADDRESS,
DROP COLUMN REPLY_TO,
DROP COLUMN SUBJECT,
ADD COLUMN USE_CC TINYINT(1) NOT NULL AFTER TRANSFER_CONFIG_ID,
ADD COLUMN USE_BCC TINYINT(1) NOT NULL AFTER USE_CC,
ADD COLUMN USE_REPLYTO TINYINT(1) NOT NULL AFTER USE_BCC;

CREATE TABLE D_TRANSFER_CONFIG_MAIL_ADDRESS (
  ID INT NOT NULL AUTO_INCREMENT,
  TRANSFER_CONFIG_MAIL_ID INT NOT NULL,
  ADDRESS_INDEX INT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  USER_GROUP VARCHAR(30) NOT NULL,
  CREATED_USER VARCHAR(45) NOT NULL,
  MODIFIED_USER VARCHAR(45) NOT NULL,
  CREATED DATETIME NOT NULL,
  MODIFIED DATETIME NOT NULL,
  PRIMARY KEY (ID),
  INDEX IDX_TRANSFER_CONFIG_MAIL_ID (TRANSFER_CONFIG_MAIL_ID ASC) VISIBLE);

# --- !Downs
ALTER TABLE D_TRANSFER_CONFIG_MAIL
ADD COLUMN BODY TEXT,
ADD COLUMN BCC_ADDRESS VARCHAR(255) DEFAULT NULL,
ADD COLUMN CC_ADDRESS VARCHAR(255) DEFAULT NULL,
ADD COLUMN TO_ADDRESS VARCHAR(255) NOT NULL,
ADD COLUMN FROM_ADDRESS VARCHAR(255) NOT NULL,
ADD COLUMN REPLY_TO VARCHAR(255) DEFAULT NULL,
ADD COLUMN SUBJECT VARCHAR(255) NOT NULL,
DROP COLUMN USE_CC,
DROP COLUMN USE_BCC,
DROP COLUMN USE_REPLYTO;

DROP TABLE D_TRANSFER_CONFIG_MAIL_ADDRESS;