# --- !Ups
CREATE TABLE D_FORM_TRANSFER_TASK_MAIL (
  ID INT NOT NULL,
  TRANSFER_TASK_ID INT NOT NULL,
  FROM_ADDRESS_ID INT NOT NULL,
  TO_ADDRESS VARCHAR(255) NOT NULL,
  CC_ADDRESS VARCHAR(255) NULL,
  BCC_ADDRESS_ID INT NULL,
  REPLYTO_ADDRESS_ID INT NULL,
  SUBJECT VARCHAR(255) NOT NULL,
  BODY TEXT NOT NULL,
  USER_GROUP VARCHAR(30) NOT NULL,
  CREATED_USER VARCHAR(45) NOT NULL,
  MODIFIED_USER VARCHAR(45) NOT NULL,
  CREATED DATETIME NOT NULL,
  MODIFIED DATETIME NOT NULL,
  PRIMARY KEY (ID),
  INDEX IDX_TRANSFER_TASK_ID (TRANSFER_TASK_ID ASC));

CREATE TABLE D_FORM_TRANSFER_TASK_SALESFORCE (
  ID INT NOT NULL,
  TRANSFER_TASK_ID INT NOT NULL,
  OBJECT_NAME VARCHAR(255) NOT NULL,
  USER_GROUP VARCHAR(30) NOT NULL,
  CREATED_USER VARCHAR(45) NOT NULL,
  MODIFIED_USER VARCHAR(45) NOT NULL,
  CREATED DATETIME NOT NULL,
  MODIFIED DATETIME NOT NULL,
  PRIMARY KEY (ID),
  INDEX IDX_TRANSFER_TASK_ID (TRANSFER_TASK_ID ASC));

CREATE TABLE D_FORM_TRANSFER_TASK_SALESFORCE_FIELD (
  ID INT NOT NULL,
  TRANSFER_TASK_SALESFORCE_ID INT NOT NULL,
  FORM_COLUMN_ID VARCHAR(45) NOT NULL,
  FIELD_NAME VARCHAR(255) NULL,
  USER_GROUP VARCHAR(30) NOT NULL,
  CREATED_USER VARCHAR(45) NOT NULL,
  MODIFIED_USER VARCHAR(45) NOT NULL,
  CREATED DATETIME NOT NULL,
  MODIFIED DATETIME NOT NULL,
  PRIMARY KEY (ID),
  INDEX IDX_TRANSFER_TASK_ID (TRANSFER_TASK_SALESFORCE_ID ASC));

# --- !Downs
DROP TABLE D_FORM_TRANSFER_TASK_MAIL;

DROP TABLE D_FORM_TRANSFER_TASK_SALESFORCE;

DROP TABLE D_FORM_TRANSFER_TASK_SALESFORCE_FIELD;
