# --- !Ups
ALTER TABLE D_FORM_TRANSFER_TASK_MAIL
CHANGE COLUMN TRANSFER_TASK_ID FORM_TRANSFER_TASK_ID INT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE
CHANGE COLUMN TRANSFER_TASK_ID FORM_TRANSFER_TASK_ID INT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE_FIELD
CHANGE COLUMN TRANSFER_TASK_SALESFORCE_ID FORM_TRANSFER_TASK_SALESFORCE_ID INT NOT NULL ;

# --- !Downs
ALTER TABLE D_FORM_TRANSFER_TASK_MAIL
CHANGE COLUMN FORM_TRANSFER_TASK_ID TRANSFER_TASK_ID INT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE
CHANGE COLUMN FORM_TRANSFER_TASK_ID TRANSFER_TASK_ID INT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE_FIELD
CHANGE COLUMN FORM_TRANSFER_TASK_SALESFORCE_ID TRANSFER_TASK_SALESFORCE_ID INT NOT NULL ;
