# --- !Ups
ALTER TABLE D_FORM_TRANSFER_TASK
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE D_FORM_TRANSFER_TASK_CONDITION
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE D_FORM_TRANSFER_TASK_MAIL
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE_FIELD
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT;

# --- !Downs
ALTER TABLE D_FORM_TRANSFER_TASK
CHANGE COLUMN ID ID INT NOT NULL;

ALTER TABLE D_FORM_TRANSFER_TASK_CONDITION
CHANGE COLUMN ID ID INT NOT NULL;

ALTER TABLE D_FORM_TRANSFER_TASK_MAIL
CHANGE COLUMN ID ID INT NOT NULL;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE
CHANGE COLUMN ID ID INT NOT NULL;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE_FIELD
CHANGE COLUMN ID ID INT NOT NULL;