# --- !Ups
ALTER TABLE D_FORM
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ;

ALTER TABLE D_FORM_COL
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_ID FORM_ID BIGINT NOT NULL ;

ALTER TABLE D_FORM_COL_SELECT
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_COL_ID FORM_COL_ID BIGINT NOT NULL ,
CHANGE COLUMN FORM_ID FORM_ID BIGINT NOT NULL ;

ALTER TABLE D_FORM_COL_VALIDATION
CHANGE COLUMN ID ID BIGINT NOT NULL ,
CHANGE COLUMN FORM_COL_ID FORM_COL_ID BIGINT NOT NULL ,
CHANGE COLUMN FORM_ID FORM_ID BIGINT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_ID TRANSFER_CONFIG_ID BIGINT NOT NULL ,
CHANGE COLUMN FORM_ID FORM_ID BIGINT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_CONDITION
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_TRANSFER_TASK_ID FORM_TRANSFER_TASK_ID BIGINT NOT NULL ,
CHANGE COLUMN FORM_ID FORM_ID BIGINT NOT NULL ,
CHANGE COLUMN FORM_COL_ID FORM_COL_ID BIGINT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_MAIL
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_TRANSFER_TASK_ID FORM_TRANSFER_TASK_ID BIGINT NOT NULL ,
CHANGE COLUMN FROM_ADDRESS_ID FROM_ADDRESS_ID BIGINT NOT NULL ,
CHANGE COLUMN BCC_ADDRESS_ID BCC_ADDRESS_ID BIGINT NULL DEFAULT NULL ,
CHANGE COLUMN REPLYTO_ADDRESS_ID REPLYTO_ADDRESS_ID BIGINT NULL DEFAULT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_TRANSFER_TASK_ID FORM_TRANSFER_TASK_ID BIGINT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE_FIELD
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_TRANSFER_TASK_SALESFORCE_ID FORM_TRANSFER_TASK_SALESFORCE_ID BIGINT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ;

ALTER TABLE D_TRANSFER_CONFIG_MAIL
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_ID TRANSFER_CONFIG_ID BIGINT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG_MAIL_ADDRESS
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_MAIL_ID TRANSFER_CONFIG_MAIL_ID BIGINT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_ID TRANSFER_CONFIG_ID BIGINT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_SALESFORCE_ID TRANSFER_CONFIG_SALESFORCE_ID BIGINT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT_FIELD
CHANGE COLUMN ID ID BIGINT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_SALESFORCE_OBJECT_ID TRANSFER_CONFIG_SALESFORCE_OBJECT_ID BIGINT NOT NULL ;

# --- !Downs
ALTER TABLE D_FORM
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ;

ALTER TABLE D_FORM_COL
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_ID FORM_ID INT NOT NULL ;

ALTER TABLE D_FORM_COL_SELECT
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_COL_ID FORM_COL_ID INT NOT NULL ,
CHANGE COLUMN FORM_ID FORM_ID INT NOT NULL ;

ALTER TABLE D_FORM_COL_VALIDATION
CHANGE COLUMN ID ID INT NOT NULL ,
CHANGE COLUMN FORM_COL_ID FORM_COL_ID INT NOT NULL ,
CHANGE COLUMN FORM_ID FORM_ID INT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_ID TRANSFER_CONFIG_ID INT NOT NULL ,
CHANGE COLUMN FORM_ID FORM_ID INT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_CONDITION
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_TRANSFER_TASK_ID FORM_TRANSFER_TASK_ID INT NOT NULL ,
CHANGE COLUMN FORM_ID FORM_ID INT NOT NULL ,
CHANGE COLUMN FORM_COL_ID FORM_COL_ID INT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_MAIL
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_TRANSFER_TASK_ID FORM_TRANSFER_TASK_ID INT NOT NULL ,
CHANGE COLUMN FROM_ADDRESS_ID FROM_ADDRESS_ID INT NOT NULL ,
CHANGE COLUMN BCC_ADDRESS_ID BCC_ADDRESS_ID INT NULL DEFAULT NULL ,
CHANGE COLUMN REPLYTO_ADDRESS_ID REPLYTO_ADDRESS_ID INT NULL DEFAULT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_TRANSFER_TASK_ID FORM_TRANSFER_TASK_ID INT NOT NULL ;

ALTER TABLE D_FORM_TRANSFER_TASK_SALESFORCE_FIELD
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN FORM_TRANSFER_TASK_SALESFORCE_ID FORM_TRANSFER_TASK_SALESFORCE_ID INT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ;

ALTER TABLE D_TRANSFER_CONFIG_MAIL
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_ID TRANSFER_CONFIG_ID INT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG_MAIL_ADDRESS
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_MAIL_ID TRANSFER_CONFIG_MAIL_ID INT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_ID TRANSFER_CONFIG_ID INT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_SALESFORCE_ID TRANSFER_CONFIG_SALESFORCE_ID INT NOT NULL ;

ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT_FIELD
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN TRANSFER_CONFIG_SALESFORCE_OBJECT_ID TRANSFER_CONFIG_SALESFORCE_OBJECT_ID INT NOT NULL ;
