name: SFORM-ADMIN-API Build and Push

on:
  push:
    branches:
      - develop-it

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  WORKLOAD_IDENTITY_POOL_ID: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
  PROVIDER_ID: ${{ secrets.PROVIDER_ID }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  SERVICE_ACCOUNT_JSON_KEY: ${{ secrets.SERVICE_ACCOUNT_JSON_KEY }}
  SFORM_GITHUB_USER: ${{ secrets.SFORM_GITHUB_USER }}
  SFORM_GITHUB_TOKEN: ${{ secrets.SFORM_GITHUB_TOKEN }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/sform2:${{ github.sha }}

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
        with:
          persist-credentials: false

      - name: 'Auth'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          workload_identity_provider: projects/$PROJECT_ID/locations/global/workloadIdentityPools/$WORKLOAD_IDENTITY_POOL_ID/providers/$PROVIDER_ID
          service_account: $SERVICE_ACCOUNT@$PROJECT_ID.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Configure Docker'
        run: |-
          gcloud auth configure-docker --quiet

      - name: 'Build'
        run: |-
          cd docker/sform2/
          docker build \
            --f Dockerfile \
            --tag "$IMAGE" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            --build-arg GITHUB_USER="$SFORM_GITHUB_USER" \
            --build-arg GITHUB_TOKEN="$SFORM_GITHUB_TOKEN" \
            --build-arg SFORM_VERSION="1.0-SNAPSHOT" \
            .

      - name: Publish
        run: |-
          echo $SERVICE_ACCOUNT_JSON_KEY | docker login -u _json_key --password-stdin https://gcr.io
          docker push "$IMAGE"

  deploy:
    name: 'deploy'
    needs: 'build'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.2.0'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_JSON_KEY }}
          export_default_credentials: true

      #- name: 'Deploy'
      #  uses: 'google-github-actions/deploy-cloudrun@v0.4.0'
      #  with:
      #    service: 'sform2'
      #    image: ${{ env.IMAGE }}
      #    region: 'asia-northeast1'
      #    --add-cloudsql-instances: ${{ env.PROJECT_ID }}:asia-northeast1:sform

      - name: 'Deploy'
        run : |-
          gcloud run deploy sform2 --service-account ${SERVICE_ACCOUNT} --image ${IMAGE} --region asia-northeast1 --platform managed --add-cloudsql-instances ${PROJECT_ID}:asia-northeast1:sform --port=9001 --ingress internal-and-cloud-load-balancing
