name: SFORM-ADMIN-API-PROD Build and Push

on:
  push:
    branches:
      - master
      - feature/SFORM-84
# 要修正

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  WORKLOAD_IDENTITY_POOL_ID: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
  PROVIDER_ID: ${{ secrets.PROVIDER_ID }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  SERVICE_ACCOUNT_JSON_KEY: ${{ secrets.SERVICE_ACCOUNT_JSON_KEY }}
  SFORM_GITHUB_USER: ${{ secrets.SFORM_GITHUB_USER }}
  SFORM_GITHUB_TOKEN: ${{ secrets.SFORM_GITHUB_TOKEN }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/sform-admin-api-prod:${{ github.sha }}

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          persist-credentials: false

      - name: 'Auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ env.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ env.PROVIDER_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: 'Set Project ID'
        run: |
          gcloud config set project $PROJECT_ID

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Configure Docker'
        run: |-
          gcloud auth configure-docker --quiet

      - name: 'Build'
        run: |-
          cd docker/sform2/
          docker build \
            --tag "$IMAGE" \
            --build-arg BRANCH="master" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            --build-arg GITHUB_USER="$SFORM_GITHUB_USER" \
            --build-arg GITHUB_TOKEN="$SFORM_GITHUB_TOKEN" \
            --build-arg SFORM_VERSION="1.0-SNAPSHOT" \
            .

      - name: Publish
        run: |-
          echo $SERVICE_ACCOUNT_JSON_KEY | docker login -u _json_key --password-stdin https://gcr.io
          docker push "$IMAGE"

  deploy:
    name: 'deploy'
    needs: 'build'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.2.0'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_JSON_KEY }}
          export_default_credentials: true

      - name: 'Deploy'
        run : |-
          gcloud run deploy sform-admin-api-prod --service-account ${SERVICE_ACCOUNT} --image ${IMAGE} --region asia-northeast1 --platform managed --add-cloudsql-instances ${PROJECT_ID}:asia-northeast1:sform --port=9001 --ingress internal-and-cloud-load-balancing
