name: Build and Push

on:
  push:
    branches:
      - develop-it

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  WORKLOAD_IDENTITY_POOL_ID: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
  PROVIDER_ID: ${{ secrets.PROVIDER_ID }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  SFORM_GITHUB_USER: ${{ secrets.SFORM_GITHUB_USER }}
  SFORM_GITHUB_TOKEN: ${{ secrets.SFORM_GITHUB_TOKEN }}
  DEPLOYMENT_NAME: gke-test
  IMAGE: sform2

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'auth'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          workload_identity_provider: projects/$PROJECT_ID/locations/global/workloadIdentityPools/$WORKLOAD_IDENTITY_POOL_ID/providers/$PROVIDER_ID
          service_account: $SERVICE_ACCOUNT@$PROJECT_ID.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Configure Docker'
        run: |-
          gcloud auth configure-docker

      - name: Build
        run: |-
          cd docker/sform2/
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            --build-arg GITHUB_USER="$SFORM_GITHUB_USER" \
            --build-arg GITHUB_TOKEN="$SFORM_GITHUB_TOKEN" \
            --build-arg SFORM_VERSION="1.0-SNAPSHOT" \
            .

      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

