# --- !Ups
CREATE TABLE `D_TRANSFER_TASKS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRANSFER_TYPE_ID` int(11) NOT NULL,
  `NAME` varchar(128) NOT NULL,
  `STATUS` int(11) NOT NULL DEFAULT 0,
  `CONFIG` json,
  `CREATED` datetime DEFAULT NULL,
  `MODIFIED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

# --- !Downs
drop table D_TRANSFER_TASKS