# --- !Ups
ALTER TABLE D_FORM
ADD COLUMN USER_GROUP VARCHAR(30) AFTER FORM_DATA;
ALTER TABLE D_POSTDATA
ADD COLUMN USER_GROUP VARCHAR(30) AFTER POSTDATA;
ALTER TABLE D_POSTDATA
ADD COLUMN CREATED_USER VARCHAR(45) AFTER USER_GROUP;
ALTER TABLE D_POSTDATA
ADD COLUMN MODIFIED_USER VARCHAR(45) AFTER CREATED;
ALTER TABLE D_TRANSFER_DETAIL_LOG
ADD COLUMN USER_GROUP VARCHAR(30) AFTER MESSAGE;
ALTER TABLE D_TRANSFER_DETAIL_LOG
ADD COLUMN CREATED_USER VARCHAR(45) AFTER USER_GROUP;
ALTER TABLE D_TRANSFER_DETAIL_LOG
ADD COLUMN MODIFIED_USER VARCHAR(45) AFTER CREATED;
ALTER TABLE D_TRANSFER_LOG
ADD COLUMN USER_GROUP VARCHAR(30) AFTER RESULT_DATA;
ALTER TABLE D_TRANSFER_LOG
ADD COLUMN CREATED_USER VARCHAR(45) AFTER USER_GROUP;
ALTER TABLE D_TRANSFER_LOG
ADD COLUMN MODIFIED_USER VARCHAR(45) AFTER CREATED;
ALTER TABLE D_TRANSFER_TASKS
ADD COLUMN USER_GROUP VARCHAR(30) AFTER CONFIG;
ALTER TABLE D_TRANSFER_TASKS
ADD COLUMN CREATED_USER VARCHAR(45) AFTER USER_GROUP;
ALTER TABLE D_TRANSFER_TASKS
ADD COLUMN MODIFIED_USER VARCHAR(45) AFTER CREATED;
ALTER TABLE M_TRANSFERS
ADD COLUMN USER_GROUP VARCHAR(30) AFTER CONFIG;
ALTER TABLE M_TRANSFERS
ADD COLUMN CREATED_USER VARCHAR(45) AFTER USER_GROUP;
ALTER TABLE M_TRANSFERS
ADD COLUMN MODIFIED_USER VARCHAR(45) AFTER CREATED;


# --- !Downs
ALTER TABLE D_FORM DROP COLUMN USER_GROUP;
ALTER TABLE D_POSTDATA DROP COLUMN USER_GROUP;
ALTER TABLE D_POSTDATA DROP COLUMN CREATED_USER;
ALTER TABLE D_POSTDATA DROP COLUMN MODIFIED_USER;
ALTER TABLE D_TRANSFER_DETAIL_LOG DROP COLUMN USER_GROUP;
ALTER TABLE D_TRANSFER_DETAIL_LOG DROP COLUMN CREATED_USER;
ALTER TABLE D_TRANSFER_DETAIL_LOG DROP COLUMN MODIFIED_USER;
ALTER TABLE D_TRANSFER_LOG DROP COLUMN USER_GROUP;
ALTER TABLE D_TRANSFER_LOG DROP COLUMN CREATED_USER;
ALTER TABLE D_TRANSFER_LOG DROP COLUMN MODIFIED_USER;
ALTER TABLE D_TRANSFER_TASKS DROP COLUMN USER_GROUP;
ALTER TABLE D_TRANSFER_TASKS DROP COLUMN CREATED_USER;
ALTER TABLE D_TRANSFER_TASKS DROP COLUMN MODIFIED_USER;
ALTER TABLE M_TRANSFERS DROP COLUMN USER_GROUP;
ALTER TABLE M_TRANSFERS DROP COLUMN CREATED_USER;
ALTER TABLE M_TRANSFERS DROP COLUMN MODIFIED_USER;
