# --- !Ups
ALTER TABLE D_FORM 
ADD COLUMN FORM_INDEX INT NOT NULL AFTER HASHED_ID,
ADD COLUMN NAME VARCHAR(255) NOT NULL AFTER FORM_INDEX,
ADD COLUMN TITLE VARCHAR(255) NOT NULL AFTER NAME,
ADD COLUMN STATUS INT NOT NULL AFTER TITLE,
ADD COLUMN CANCEL_URL VARCHAR(255) NOT NULL AFTER STATUS,
ADD COLUMN COMPLETE_URL VARCHAR(255) NOT NULL AFTER CANCEL_URL,
ADD COLUMN INPUT_HEADER LONGTEXT NULL AFTER COMPLETE_URL,
ADD COLUMN CONFIRM_HEADER LONGTEXT NULL AFTER INPUT_HEADER,
ADD COLUMN COMPLETE_TEXT LONGTEXT NULL AFTER CONFIRM_HEADER,
ADD COLUMN CLOSE_TEXT LONGTEXT NULL AFTER COMPLETE_TEXT;

# --- !Downs
ALTER TABLE D_FORM
DELETE COLUMN FORM_INDEX,
DELETE COLUMN NAME,
DELETE COLUMN TITLE,
DELETE COLUMN STATUS,
DELETE COLUMN CANCEL_URL,
DELETE COLUMN COMPLETE_URL,
DELETE COLUMN INPUT_HEADER,
DELETE COLUMN CONFIRM_HEADER,
DELETE COLUMN COMPLETE_TEXT,
DELETE COLUMN CLOSE_TEXT
