# --- !Ups
ALTER TABLE D_AUTHTOKEN
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE D_FORM
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE D_FORM_COL
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE D_FORM_COL_SELECT
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE D_FORM_COL_VALIDATION
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE D_POSTDATA
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE D_TRANSFER_DETAIL_LOG
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE D_TRANSFER_LOG
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE D_TRANSFER_TASKS
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE M_AUTHINFO
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE M_TRANSFERS
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE M_USER
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE M_USERINFO
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;
ALTER TABLE PLAY_EVOLUTIONS
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_bin ;

# --- !Downs
ALTER TABLE D_AUTHTOKEN
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE D_FORM
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE D_FORM_COL
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_0900_ai_ci ;
ALTER TABLE D_FORM_COL_SELECT
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_0900_ai_ci ;
ALTER TABLE D_FORM_COL_VALIDATION
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_0900_ai_ci ;
ALTER TABLE D_POSTDATA
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE D_TRANSFER_DETAIL_LOG
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE D_TRANSFER_LOG
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE D_TRANSFER_TASKS
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE M_AUTHINFO
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE M_TRANSFERS
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE M_USER
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE M_USERINFO
CHARACTER SET = utf8 , COLLATE = utf8_bin ;
ALTER TABLE PLAY_EVOLUTIONS
CHARACTER SET = utf8mb4 , COLLATE = utf8mb4_0900_ai_ci ;
