# --- !Ups
ALTER TABLE M_TRANSFERS 
DROP COLUMN USER_GROUP,
DROP COLUMN CONFIG,
DROP COLUMN TYPE_ID,
ADD COLUMN TYPE_CODE VARCHAR(45) NOT NULL AFTER ID,
CHANGE COLUMN STATUS STATUS INT NOT NULL ,
CHANGE COLUMN CREATED_USER CREATED_USER VARCHAR(45) NOT NULL ,
CHANGE COLUMN CREATED CREATED DATETIME NOT NULL ,
CHANGE COLUMN MODIFIED_USER MODIFIED_USER VARCHAR(45) NOT NULL ,
CHANGE COLUMN MODIFIED MODIFIED DATETIME NOT NULL ;

# --- !Downs
ALTER TABLE M_TRANSFERS
ADD COLUMN UER_GROUP VARCHAR(30) DEFAULT NULL,
ADD COLUMN CONFIG JSON DEFAULT NULL,
ADD COLUMN TYPE_ID INT DEFAULT NULL,
DROP COLUMN TYPE_CODE,
CHANGE COLUMN STATUS STATUS INT DEFAULT 1,
CHANGE COLUMN CREATED_USER CREATED_USER VARCHAR(45) DEFAULT NULL,
CHANGE COLUMN CREATED CREATED DATETIME DEFAULT NULL,
CHANGE COLUMN MODIFIED_USER MODIFIED_USER VARCHAR(45) DEFAULT NULL,
CHANGE COLUMN MODIFIED MODIFIED DATETIME DEFAULT NULL;