# --- !Ups
ALTER TABLE D_FORM_COL_VALIDATION 
ADD COLUMN REQUIRED TINYINT(1) NULL AFTER INPUT_TYPE;

CREATE TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT (
  ID INT NOT NULL,
  TRANSFER_CONFIG_SALESFORCE_ID INT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  LABEL VARCHAR(255) NOT NULL,
  ACTIVE TINYINT(1) NOT NULL,
  USER_GROUP VARCHAR(30) NOT NULL,
  CREATED_USER VARCHAR(45) NOT NULL,
  MODIFIED_USER VARCHAR(45) NOT NULL,
  CREATED DATETIME NOT NULL,
  MODIFIED DATETIME NOT NULL,
  PRIMARY KEY (ID),
  INDEX IDX_TRANSFER_CONFIG_SALESFORCE_ID (TRANSFER_CONFIG_SALESFORCE_ID ASC));

CREATE TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT_FIELD (
  ID INT NOT NULL,
  TRANSFER_CONFIG_SALESFORCE_FIELD_ID INT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  LABEL VARCHAR(255) NOT NULL,
  FIELD_TYPE VARCHAR(30) NOT NULL,
  ACTIVE TINYINT(1) NOT NULL,
  USER_GROUP VARCHAR(30) NOT NULL,
  CREATED_USER VARCHAR(45) NOT NULL,
  MODIFIED_USER VARCHAR(45) NOT NULL,
  CREATED DATETIME NOT NULL,
  MODIFIED DATETIME NOT NULL,
  PRIMARY KEY (ID),
  INDEX IDX_TRANSFER_CONFIG_SALESFORCE_OBJECT_ID (TRANSFER_CONFIG_SALESFORCE_FIELD_ID ASC));

# --- !Downs
ALTER TABLE D_FORM_COL_VALIDATION
DROP COLUMN REQUIRED;

DROP TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT;

DROP TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT_FIELD;
