# --- !Ups
ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT_FIELD 
CHANGE COLUMN TRANSFER_CONFIG_SALESFORCE_FIELD_ID TRANSFER_CONFIG_SALESFORCE_OBJECT_ID INT NOT NULL ;

# --- !Downs
ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT_FIELD
CHANGE COLUMN TRANSFER_CONFIG_SALESFORCE_OBJECT_ID TRANSFER_CONFIG_SALESFORCE_FIELD_ID INT NOT NULL ;