# --- !Ups
ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ;

ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT_FIELD
CHANGE COLUMN ID ID INT NOT NULL AUTO_INCREMENT ;

# --- !Downs
ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT
CHANGE COLUMN ID ID INT NOT NULL;

ALTER TABLE D_TRANSFER_CONFIG_SALESFORCE_OBJECT_FIELD
CHANGE COLUMN ID ID INT NOT NULL;
