# --- !Ups
ALTER TABLE `sform`.`m_userinfo`
CHANGE COLUMN `LINKED_ID` `LINKEDID` VARCHAR(255) NULL DEFAULT NULL ;

# --- !Downs
ALTER TABLE `sform`.`m_userinfo`
CHANGE COLUMN `LINKEDID` `LINKED_ID` VARCHAR(255) NULL DEFAULT NULL ;
